# Generated by Django 5.1.2 on 2024-11-03 02:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(db_column='Customer_ID', primary_key=True, serialize=False)),
                ('customer_fn', models.CharField(db_column='CustomerFN', max_length=30)),
                ('customer_ln', models.CharField(db_column='CustomerLN', max_length=30)),
                ('membership_start_date', models.DateField(db_column='Membership_Start_Date')),
                ('membership_end_date', models.DateField(db_column='Membership_End_Date', null=True)),
                ('street_address', models.CharField(db_column='Street_Address', max_length=30)),
                ('city', models.CharField(db_column='City', max_length=30)),
                ('state', models.CharField(db_column='State', max_length=5)),
                ('zip_code', models.IntegerField(db_column='Zip_Code')),
                ('phone_number', models.CharField(db_column='Phone_Number', max_length=30)),
                ('email', models.CharField(db_column='Email', max_length=30)),
                ('outstanding_fines', models.DecimalField(db_column='Outstanding_Fines', decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'Customer',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('item_id', models.AutoField(db_column='Item_ID', primary_key=True, serialize=False)),
                ('title', models.CharField(db_column='Title', max_length=32)),
                ('author_fn', models.CharField(db_column='AuthorFN', max_length=32)),
                ('author_ln', models.CharField(db_column='AuthorLN', max_length=32)),
                ('publisher', models.CharField(db_column='Publisher', max_length=32, null=True)),
                ('loc_code', models.CharField(db_column='Loc_Code', max_length=32)),
                ('cost', models.DecimalField(db_column='Cost', decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'Item',
            },
        ),
        migrations.CreateModel(
            name='CheckOut',
            fields=[
                ('check_out_id', models.AutoField(db_column='Check_Out_ID', primary_key=True, serialize=False)),
                ('checkout_date', models.DateField(db_column='Checkout_Date')),
                ('due_date', models.DateField(db_column='Due_Date')),
                ('returned', models.BooleanField(db_column='Returned')),
                ('customer', models.ForeignKey(db_column='Customer_ID', on_delete=django.db.models.deletion.CASCADE, to='books.customer')),
            ],
            options={
                'db_table': 'Check_Out',
            },
        ),
        migrations.CreateModel(
            name='ItemIsCheckedOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_out', models.ForeignKey(db_column='Check_Out_ID', on_delete=django.db.models.deletion.CASCADE, to='books.checkout')),
                ('item', models.ForeignKey(db_column='Item_ID', on_delete=django.db.models.deletion.CASCADE, to='books.item')),
            ],
            options={
                'db_table': 'Item_Is_Checked_Out',
            },
        ),
    ]
