# Generated by Django 5.1.2 on 2024-11-13 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_checkout_returned_fines_librarycard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fines',
            name='amount',
            field=models.DecimalField(db_column='Fine_Amount', decimal_places=2, max_digits=10),
        ),
        migrations.AlterModelTable(
            name='fines',
            table='fine',
        ),
    ]
