# Generated by Django 5.1.2 on 2024-11-21 16:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_checkout_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckIn',
            fields=[
                ('check_in_id', models.AutoField(db_column='Check_In_ID', primary_key=True, serialize=False)),
                ('return_date', models.DateField(db_column='Return_Date', null=True)),
                ('late_fees', models.FloatField(db_column='Late_Fees', default=0.0)),
                ('customer', models.ForeignKey(db_column='Customer_ID', on_delete=django.db.models.deletion.CASCADE, to='books.customer')),
                ('item', models.ForeignKey(db_column='Item_ID', on_delete=django.db.models.deletion.CASCADE, to='books.item')),
            ],
            options={
                'db_table': 'check_in',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('reservation_id', models.AutoField(db_column='Reservation_ID', primary_key=True, serialize=False)),
                ('reservation_date', models.DateField(db_column='Reservation_Date', null=True)),
                ('status', models.CharField(choices=[('Reserved', 'Reserved'), ('Cancelled', 'Cancelled'), ('PickedUp', 'PickedUp')], default='Reserved', max_length=20)),
                ('is_active', models.BooleanField(db_column='Is_Active', default=True)),
                ('queue_position', models.IntegerField(db_column='Queue_Position', default=0)),
                ('customer', models.ForeignKey(db_column='Customer_ID', on_delete=django.db.models.deletion.CASCADE, to='books.customer')),
                ('item', models.ForeignKey(db_column='Item_ID', on_delete=django.db.models.deletion.CASCADE, to='books.item')),
            ],
            options={
                'db_table': 'reservation',
            },
        ),
    ]
