# Generated by Django 5.1.2 on 2024-11-22 02:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_checkin_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='notification_deadline',
            field=models.DateField(db_column='Notification_Deadline', null=True),
        ),
        migrations.AddField(
            model_name='reservation',
            name='notification_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Notified', 'Notified'), ('Expired', 'Expired')], db_column='Notification_Status', default='Pending', max_length=20),
        ),
        migrations.AddField(
            model_name='reservation',
            name='notified_on',
            field=models.DateField(db_column='Notified_On', null=True),
        ),
    ]
