# Generated by Django 5.1.2 on 2024-11-23 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_reservation_notification_deadline_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('Reserved', 'Reserved'), ('Cancelled', 'Cancelled'), ('PickedUp', 'PickedUp'), ('FullFilled', 'Fullfilled')], default='Reserved', max_length=20),
        ),
    ]
